### ISSUE TITLE
Gemfile and Gemfile.lock interferring with pod install

### ISSUE THREAD

**Issue by warpling** [ObjectiveToast/CustomTransitions#1]
I think the Gemfile(and .lock) are unnecessary and might be causing warnings when trying to run `pod install` via newer version of cocoapods! I'm not 100% sure, but removing both gemfiles allowed me to run `pod install` without error.

```
~/Downloads/CustomTransitions-master () pod install
Setting up CocoaPods master repo
Already up-to-date.
[!] The `master` repo requires CocoaPods 0.32.1 - 
Update CocoaPods, or checkout the appropriate tag in the repo.
/Users/ryanmcleod/.rvm/gems/ruby-2.1.1/gems/claide-0.4.0/lib/claide/command.rb:217:in `rescue in run': undefined method `verbose?' for nil:NilClass (NoMethodError)
    from /Users/ryanmcleod/.rvm/gems/ruby-2.1.1/gems/claide-0.4.0/lib/claide/command.rb:210:in `run'
    from /Users/ryanmcleod/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.29.0/lib/cocoapods/command.rb:51:in `run'
    from /Users/ryanmcleod/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.29.0/bin/pod:24:in `<top (required)>'
    from /Users/ryanmcleod/.rvm/gems/ruby-2.1.1/bin/pod:23:in `load'
    from /Users/ryanmcleod/.rvm/gems/ruby-2.1.1/bin/pod:23:in `<main>'
    from /Users/ryanmcleod/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
    from /Users/ryanmcleod/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by macdrevx** [comment]
@warpling Agreed. I'll remove them.

**Comment by macdrevx** [comment]
@warpling Updated on master. I also checked in the Pods directory, so there shouldn't be a need to run `pod install` anymore.

**Comment by warpling** [comment]
Good call!
